### ISSUE TITLE
Infografía Realidad Aumentada

### ISSUE THREAD

**Issue by antoniio** [SistemasTecTlaxiaco/infografia-antoniio#1]
[Infografia realidad aumentada.pdf](https://github.com/SistemasTecTlaxiaco/infografia-antoniio/files/8061812/Infografia.realidad.aumentada.pdf)

**Comment by Nancy2050** [comment]
Puntaje 18/20 (90%)
Faltan fuentes

**Comment by josealfredo79** [comment]
Bien hecho y revisado
