### ISSUE TITLE
Infografía de ingeniería de requisitos Antonio Cruz Chávez

### ISSUE THREAD

**Issue by antoniio** [SistemasTecTlaxiaco/infografia-antoniio#2]
![1](https://user-images.githubusercontent.com/79992182/110150813-4a9fe200-7da5-11eb-8061-36f28c1af8ec.jpg)
![2](https://user-images.githubusercontent.com/79992182/110150888-65725680-7da5-11eb-8327-9c3635f1c014.jpg)

**Comment by ElvisS10** [comment]
Excelente trabajo! La infografía esta bien diseñada 
**Calificación: 20%**

**Comment by ThorSampy** [comment]
Este trabajo esta elaborado en buena forma.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
